import { Inter } from "next/font/google";
import "./globals.css";

// import 'react-toastify/ReactToastify.css';

import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"]
 });



export const metadata = {
  title: "Todo Next5 App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        
        {children}
        
      </body>
    </html>
  );
}

//npm install @vercel/otel @opentelemetry/sdk-logs @opentelemetry/api-logs @opentelemetry/instrumentation